version: '3.8'

services:
  ##############################
  #   Citus coordinator node   #
  ##############################
  coordinator:
    image: lucasfs/citus-coordinator-armhf
    environment:
      &auth-conf
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ycsb"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    deploy:
      labels:
        com.citusdata.role: "Coordinator"
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == coordinator
    volumes:
      - /mnt/storage/pgdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        mode: host
    networks:
      - cluster_net

  #########################
  #   Citus worker node   #
  #########################
  worker:
    image: 'lucasfs/citus-worker-armhf'
    environment:
      << : *auth-conf
      COORDINATOR_SERVICE: "coordinator"
    deploy:
      labels:
        com.citusdata.role: "Worker"
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == worker
    volumes: 
      - /mnt/storage/pgdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        mode: host
    networks:
      - cluster_net

  #####################################
  #   Citus membership manager node   #
  #####################################
  manager:
    image: lucasfs/membership-manager-armhf
    environment:
      << : *auth-conf
      COORDINATOR_SERVICE: "coordinator"
      WORKER_SERVICE: "worker"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == coordinator
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
    networks:
      - cluster_net

networks:
  cluster_net:
    external: true
    name: citus-net  
    
