version: '3.8'

services:
  master:
    image: lucasfs/citus-armhf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == master
    volumes:
      - /mnt/storage/pgdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        mode: host
    networks:
      - cluster_net

  worker:
    image: 'lucasfs/citus-armhf'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == slave
    volumes: 
      - /mnt/storage/pgdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        mode: host
    networks:
      - cluster_net

  manager:
    image: lucasfs/membership-manager-armhf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == master
    networks:
      - cluster_net

networks:
  cluster_net:
    external: true
    name: citus-net  
    
